"""Movie and Series Database
Contains popular titles, mood-based keywords, and action categories with streaming platforms.
"""

POPULAR_TITLES = {
    "series": {
        "Stranger Things": "Netflix",
        "Breaking Bad": "Netflix",
        "Dark": "Netflix",
        "Wednesday": "Netflix",
        "Game of Thrones": "Disney+ Hotstar",
        "Squid Game": "Netflix",
        "Money Heist": "Netflix",
        "The Witcher": "Netflix",
        "The Boys": "Prime Video",
        "Peaky Blinders": "Netflix",
        "Narcos": "Netflix",
        "The Walking Dead": "Netflix",
        "Lucifer": "Netflix",
        "Better Call Saul": "Netflix",
        "Alias": "Disney+ Hotstar",
        "Alice in Borderland": "Netflix",
        "The Mandalorian": "Disney+ Hotstar",
        "House of the Dragon": "Disney+ Hotstar",
        "From": "Prime Video",
        "The Last of Us": "HBO Max",
        "The Crown": "Netflix",
        "Ozark": "Netflix",
        "Mindhunter": "Netflix",
        "Chernobyl": "HBO Max",
        "Succession": "HBO Max",
        "Westworld": "HBO Max",
        "True Detective": "HBO Max",
        "The Handmaid's Tale": "Hulu",
        "Dexter": "Prime Video",
        "IT's Welcome to Derry": "HBO Max",
        "Vikings": "Netflix"

    },
    "movie": {
        "Inception": "Prime Video",
        "Interstellar": "Prime Video",
        "The Dark Knight": "Prime Video",
        "John Wick": "Prime Video",
        "Extraction": "Netflix",
        "The Gray Man": "Netflix",
        "Fight Club": "Prime Video",
        "Gladiator": "Prime Video",
        "The Wolf of Wall Street": "Netflix",
        "Django Unchained": "Netflix",
        "The Matrix": "Prime Video",
        "Tenet": "Prime Video",
        "The Lord of the Rings: The Fellowship of the Ring": "Prime Video",
        "Dune": "Prime Video",
        "The Lord of the Rings: The Two Towers": "Prime Video",
        "Dune: Part Two": "Prime Video",
        "The Lord of the Rings: The Return of the King": "Prime Video",
        "Mad Max: Fury Road": "Prime Video",
        "Parasite": "Netflix",
        "Knives Out": "Netflix",
        "Avatar": "Prime Video",
        "Avatar: The Way of Water": "Prime Video",
        "The Prestige": "Netflix",
        "Prisoners": "Prime Video",
        "Se7en": "Netflix",
        "Shutter Island": "Netflix",
        "The Sixth Sense": "Hulu",
        "F1: Drive to Survive": "Netflix",
        "Oppenheimer": "Prime Video"
    }
}

MOOD_KEYWORDS = {
    "happy": ["Comedy", "Adventure", "Family", "Fantasy"],
    "sad": ["Drama", "Biography", "Romance"],
    "romantic": ["Romance", "Drama", "Musical"],
    "scared": ["Horror", "Thriller", "Mystery"],
    "energetic": ["Action", "Thriller", "Crime", "Sci-Fi"],
    "relaxed": ["Comedy", "Slice of Life", "Family"]
}

ACTION_CATEGORIES = {
    "marvel": {
        "Iron Man": "Disney+ Hotstar",
        "Iron Man 2": "Disney+ Hotstar",
        "Iron Man 3": "Disney+ Hotstar",
        "The Incredible Hulk": "Disney+ Hotstar",
        "Thor": "Disney+ Hotstar",
        "Thor: The Dark World": "Disney+ Hotstar",
        "Thor: Ragnarok": "Disney+ Hotstar",
        "Captain America: The First Avenger": "Disney+ Hotstar",
        "Captain America: The Winter Soldier": "Disney+ Hotstar",
        "Captain America: Civil War": "Disney+ Hotstar",
        "Doctor Strange": "Disney+ Hotstar",
        "Doctor Strange in the Multiverse of Madness": "Disney+ Hotstar",
        "Black Panther": "Disney+ Hotstar",
        "Ant-Man": "Disney+ Hotstar",
        "Ant-Man and the Wasp": "Disney+ Hotstar",
        "Guardians of the Galaxy": "Disney+ Hotstar",
        "Guardians of the Galaxy Vol. 2": "Disney+ Hotstar",
        "Guardians of the Galaxy Vol. 3": "Disney+ Hotstar",
        "Avengers": "Disney+ Hotstar",
        "Avengers: Age of Ultron": "Disney+ Hotstar",
        "Avengers: Infinity War": "Disney+ Hotstar",
        "Avengers: Endgame": "Disney+ Hotstar",
        "Spider-Man: Homecoming": "Netflix",
        "Spider-Man: Far From Home": "Netflix",
        "Spider-Man: No Way Home": "Netflix",
        "Amazing Spider-Man": "Netflix",
        "Amazing Spider-Man 2": "Netflix",
        "Black Widow": "Disney+ Hotstar",
        "Shang-Chi and the Legend of the Ten Rings": "Disney+ Hotstar",
        "Eternals": "Disney+ Hotstar",
        "Doctor Strange in the Multiverse of Madness": "Disney+ Hotstar",
        "Thor: Love and Thunder": "Disney+ Hotstar",
        "Spider-Man: Across the Spider-Verse": "Netflix",
        "Venom": "Netflix",
        "Venom: Let There Be Carnage": "Netflix",
        "Venom: The Last Dance": "Netflix",
        "Captain Marvel": "Disney+ Hotstar"
    },
    "dc": {
        "Batman Begins": "Prime Video",
        "The Dark Knight": "Prime Video",
        "The Dark Knight Rises": "Prime Video",
        "Man of Steel": "Prime Video",
        "Batman v Superman: Dawn of Justice": "Prime Video",
        "Justice League": "Prime Video",
        "Zack Snyder's Justice League": "Prime Video",
        "Wonder Woman": "Prime Video",
        "Wonder Woman 1984": "Prime Video",
        "Aquaman": "Prime Video",
        "Aquaman and the Lost Kingdom": "Prime Video",
        "Shazam!": "Prime Video",
        "Black Adam": "Prime Video",
        "Joker": "Prime Video",
        "The Batman": "Prime Video",
        "Superman": "Prime Video",
        "Superman II": "Prime Video",
        "Superman III": "Prime Video",
        "Superman IV: The Quest for Peace": "Prime Video",
        "Superman Returns": "Prime Video",
        "Justice League: War": "Prime Video",
        "Justice League: Throne of Atlantis": "Prime Video",
        "Justice League: Gods and Monsters": "Prime Video",
        "The Flash": "Prime Video"
    },
    "spy": {
        "Casino Royale": "Prime Video",
        "Quantum of Solace": "Prime Video",
        "Skyfall": "Prime Video",
        "Spectre": "Prime Video",
        "No Time to Die": "Prime Video",
        "Mission: Impossible": "Prime Video",
        "Mission: Impossible II": "Prime Video",
        "Mission: Impossible III": "Prime Video",
        "Mission: Impossible – Ghost Protocol": "Prime Video",
        "Mission: Impossible – Rogue Nation": "Prime Video",
        "Mission: Impossible – Fallout": "Prime Video",
        "The Bourne Identity": "Prime Video",
        "The Bourne Supremacy": "Prime Video",
        "The Bourne Ultimatum": "Prime Video",
        "Jason Bourne": "Prime Video"
    },
    "war": {
        "Saving Private Ryan": "Prime Video",
        "Dunkirk": "Prime Video",
        "1917": "Prime Video",
        "Hacksaw Ridge": "Prime Video",
        "Black Hawk Down": "Prime Video",
        "Fury": "Prime Video",
        "Lone Survivor": "Prime Video",
        "American Sniper": "Prime Video",
        "Full Metal Jacket": "Prime Video",
        "Platoon": "Prime Video",
        "Apocalypse Now": "Prime Video",
        "The Hurt Locker": "Prime Video",
        "We Were Soldiers": "Prime Video",
        "Enemy at the Gates": "Prime Video"
    },
    "full action": {
        "Transformers": "Prime Video",
        "Transformers: Revenge of the Fallen": "Prime Video",
        "Transformers: Dark of the Moon": "Prime Video",
        "Transformers: Age of Extinction": "Prime Video",
        "Transformers: The Last Knight": "Prime Video",
        "Bumblebee": "Prime Video",
        "Transformers: Rise of the Beasts": "Prime Video",
        "The Fast and the Furious": "Prime Video",
        "2 Fast 2 Furious": "Prime Video",
        "The Fast and the Furious: Tokyo Drift": "Prime Video",
        "Fast & Furious": "Prime Video",
        "Fast Five": "Prime Video",
        "Fast & Furious 6": "Prime Video",
        "Furious 7": "Prime Video",
        "The Fate of the Furious": "Prime Video",
        "F9": "Prime Video",
        "Fast X": "Prime Video",
        "Jurassic Park": "Prime Video",
        "Jurassic World": "Prime Video",
        "Jurassic World: Fallen Kingdom": "Prime Video",
        "Jurassic World: Dominion": "Prime Video",
        "Rise of the Planet of the Apes": "Prime Video",
        "Dawn of the Planet of the Apes": "Prime Video",
        "War for the Planet of the Apes": "Prime Video",
        "King Kong": "Prime Video",
        "Kong: Skull Island": "Prime Video",
        "Godzilla": "Prime Video",
        "Godzilla: King of the Monsters": "Prime Video",
        "Godzilla vs. Kong": "Prime Video",
        "Godzilla x Kong: The New Empire": "Prime Video",
        "Terminator": "Prime Video",
        "Terminator 2: Judgment Day": "Prime Video",
        "Terminator 3: Rise of the Machines": "Prime Video",
        "Terminator Salvation": "Prime Video",
        "Terminator Genisys": "Prime Video",
        "Terminator: Dark Fate": "Prime Video",
        "Terminator: The Sarah Connor Chronicles": "Prime Video",
        "Pacific Rim": "Prime Video",
        "Pacific Rim: Uprising": "Prime Video"
    }
}

HORROR_TITLES = {
    "The Shining": "Prime Video",
    "The Exorcist": "Netflix",
    "Hereditary": "Netflix",
    "A Quiet Place": "Paramount+",
    "The Ring": "HBO Max",
    "The Conjuring": "Prime Video",
    "Insidious": "Netflix",
    "Sinister": "Netflix",
    "The Silence of the Lambs": "Hulu",
    "Psycho": "HBO Max",
    "Scream": "Paramount+",
    "It Follows": "HBO Max",
    "The Witch": "Netflix",
    "Midsommar": "Netflix",
    "Suspiria": "Prime Video",
    "The Descent": "Netflix",
    "Evil Dead (2013)": "Prime Video",
    "Don't Breathe": "Netflix",
    "A Dark Song": "Shudder",
    "Lights Out": "Netflix",
    "Ouija": "Netflix",
    "Insidious: The Last Key": "Netflix",
    "Annabelle Comes Home": "HBO Max",
    "The Nun": "HBO Max",
    "Scary Stories to Tell in the Dark": "Paramount+"
}

THRILLER_TITLES = {
    "Se7en": "Netflix",
    "Gone Girl": "Netflix",
    "Prisoners": "Prime Video",
    "Zodiac": "Netflix",
    "The Girl on the Train": "Netflix",
    "Knives Out": "Netflix",
    "Shutter Island": "Netflix",
    "The Silence of the Lambs": "Hulu",
    "Memento": "HBO Max",
    "Inception": "Prime Video",
    "Interstellar": "Prime Video",
    "Tenet": "Prime Video",
    "The Prestige": "Netflix",
    "Parasite": "Netflix",
    "Nightcrawler": "Netflix",
    "Mystic River": "Prime Video",
    "Oldboy": "Netflix",
    "Dark City": "HBO Max",
    "Mulholland Drive": "Netflix",
    "Enemy": "Netflix"
}

ROMANTIC_TITLES = {
    "The Notebook": "Netflix",
    "Titanic": "Prime Video",
    "La La Land": "Netflix",
    "Pride and Prejudice": "Prime Video",
    "The Fault in Our Stars": "Netflix",
    "About Time": "Netflix",
    "Crazy, Stupid, Love": "Netflix",
    "The Proposal": "Netflix",
    "Eternal Sunshine of the Spotless Mind": "Netflix",
    "Before Sunrise": "Prime Video",
    "You've Got Mail": "Netflix",
    "Roman Holiday": "HBO Max",
    "Breakfast at Tiffany's": "Hulu",
    "Singin' in the Rain": "HBO Max",
    "West Side Story": "Disney+",
    "Notting Hill": "Prime Video",
    "10 Things I Hate About You": "Netflix",
    "A Walk to Remember": "Netflix",
    "The Princess Bride": "Prime Video",
    "Sleepless in Seattle": "Netflix"
}
